### ISSUE TITLE
breakdown front page of webapp into razor components

### ISSUE THREAD

**Issue by douglaskline** [douglaskline/trucktrackrepo#231]
components:

header
3-tab container with these items:
1. nearby 
2. report
3. find
footer

**Comment by douglaskline** [comment]
after talking through with @LindsayKness 
just break down the _layout.css file to 3 razor component pieces:
* title bar
* nav bar
* footer

**Comment by LindsayKness** [comment]
use <partial name = "_ParticalName.cshtml" /> 
Make sure to have names the same and that it follows the format
