### ISSUE TITLE
seed the database with Wilmington food trucks

### ISSUE THREAD

**Issue by douglaskline** [douglaskline/trucktrackrepo#261]

**Comment by douglaskline** [comment]
we need to fill out the truck table in the database with 10-15 local food trucks, so we have something to work with

https://docs.microsoft.com/en-us/ef/core/modeling/data-seeding

The data seeding should all occur in the TruckEntityTypeConfiguration.cs file

The seeding will occur when the migration occurs

This depends on issue #232

**Comment by AysunKaramustafaoglu** [comment]
@douglaskline  i added total 11 truck information into the Truck.sql file under migrations.
i need you to check please if i did correct, i will make a pull request now
